version: '3.8'
services:
  gateway:
    build:
    image:
    container_name: chun_chul
    ports:
      - "8080:8080"
    depends_on:
    environment:
      - SHAREIT_SERVER_URL=http://server:9090

  server:
    build:
    image:
    container_name: pulpulcha
    ports:
      - "9090:9090"
    depends_on:
    environment:
      - SPRING_DATASOURCE_URL=jdbc:postgresql://db:5432/shareit

  db:
    image: postgres:14
    container_name: db
    ports:
      - "6541:5432"
    environment:
      - POSTGRES_DB=shareIt
      - POSTGRES_USER=root
      - POSTGRES_PASSWORD=root